# Generated by Django 3.0.5 on 2020-04-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('spirit', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('subcat', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, max_length=20, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('abv', models.TextField(blank=True, max_length=20, null=True)),
                ('primary', models.TextField(blank=True, null=True)),
                ('secondary', models.TextField(blank=True, null=True)),
                ('tasting', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inBottle', models.TextField(blank=True, null=True)),
                ('brandParent', models.TextField(blank=True, null=True)),
                ('distillery', models.TextField(blank=True, null=True)),
                ('maturationType', models.TextField(blank=True, null=True)),
                ('mash', models.TextField(blank=True, null=True)),
                ('yeast', models.TextField(blank=True, null=True)),
                ('still', models.TextField(blank=True, null=True)),
                ('char', models.TextField(blank=True, null=True)),
                ('condenser', models.TextField(blank=True, null=True)),
                ('grainStrand', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
